### ISSUE TITLE
Affichage des utilisateurs VPN

### ISSUE THREAD

**Issue by wileck** [bugsounet/MMM-Freebox#10]
Bonjour,

J'ai un peu de code qui récupère les utilisateurs connectés au serveur VPN de la freebox.
Ca vous intéresse d'ajouter cette fonctionnalité?

Le chemin de l'api est le suivant :
`/api/v6/vpn/connection/`

Les données retournées (utiles):

```
    "result": [
        {
            "rx_bytes": 454554, (C'est le cumul de trafic à afficher en Go/Mo/Ko)
            "authenticated": true,
            "tx_bytes": 14588, (afficher en Go/Mo/Ko)
            "user": "test", (login)
            "id": "pptp-2", 
            "vpn": "pptp", (type de VPN)
            "src_ip": "93.184.216.1", (IP publique du client)
            "auth_time": 1392895500, (date de connexion)
            "local_ip": "192.168.0.57" (IP locale)
        }
    ]

```
Bonne journée!

**Comment by bugsounet** [comment]
si vous voulez, vous pouvez faire un `Pull Request` avec votre code modifié avec cette fonctionnalitée

**Comment by wileck** [comment]
Le code dont je parle je l'ai fais pour un autre module : MMM-FreeBox-Monitor.
J'ai commencé à le convertir, la philosophie de votre code est différente mais j’apprends beaucoup du coup!
Sur le MMM-FreeBox-Monitor ça doit commencer à ressembler à quelque chose, mais au niveau du node_helper.js ça semble plus ardus.

(C'est la première fois que je contribue à un dépôt git, je tâtonne!) ;)

**Comment by bugsounet** [comment]
si vous faites un PR, envoyez le sur la branch dev.
J'inspecterai :)
