### ISSUE TITLE
Erreur 403

### ISSUE THREAD

**Issue by devozanges** [bugsounet/MMM-Freebox#12]
Salut,
tout d'abord merci pour ton module qui est simple et sympa.

j'ai un petit retour 403 dans les logs, ca doit pas etre bien méchant mais bon.

`[2020-05-04 14:05:07.517] [LOG]    [Freebox] Error: Request failed with status code 403
[2020-05-04 14:06:12.513] [LOG]    [Freebox] Error: Request failed with status code 403
[2020-05-04 14:08:57.512] [LOG]    [Freebox] Error: Request failed with status code 403
[2020-05-04 14:12:26.150] [LOG]    [Freebox] Error: Request failed with status code 403
[2020-05-04 14:12:57.431] [LOG]    [Freebox] Error: Request failed with status code 403`

c'est surement un caprice de la freebox mais sinon si tu as une idée d'ou ca peut venir et éventuellement de rajouter une option permettant de ne pas remonter ces infos dans les logs je suis pas contre =)

merci a toi, bonne journée

**Comment by bugsounet** [comment]
oui, c'est un caprice de la Freebox qui ne veux pas donner accès.
il faudrait que je rajoute un option pour ça ou ignorer cette erreur...
J'ai moins d'erreur 403 quand je mets le delai de scan à 5 secs.

bref je regarderai quand je me replongerai dans l'API ;)
Pour le moment, c'est pas trop méchant...

Je préfère finir mon `Assistant2Display` avant de revenir sur `Freebox` et d'y apporter des nouvelles fonctions ;)

**Comment by devozanges** [comment]
pas de soucis, oui c'est pas méchant pour le moment a interval  5000 j'ai environ une 403 toutes les 2 ou 3minutes.
une option du genre ignore403: true/false serait bien en effet
bon courage pour ton assistant, merci pour ton taf ;)

**Comment by bugsounet** [comment]
je vais le patché, je vais mettre uniquement les erreurs si le debug est activé (pour l'instant)

**Comment by bugsounet** [comment]
voila ça doit etre good ;)

**Comment by devozanges** [comment]
merci, je pull ca dans la soirée
