### ISSUE TITLE
Afficher adresse IP pour les clients

### ISSUE THREAD

**Issue by BlackCatDeployment** [bugsounet/MMM-Freebox#16]
Hello,

Tout d'abord bravo pour ton module ! Il fonctionne super bien sur mon MagicMirror !
Pour info, j'ai une Freebox One r2 avec la fibre et les infos remontent correctement ;)
![image](https://user-images.githubusercontent.com/12493050/82731735-35236500-9d09-11ea-9a48-563961d9cd4e.png)

Comme nouvelle fonctionnalité, serait-il possible d'afficher l'adresse IP allouée à chaque client, ainsi que le mode de connexion (filaire, wifi) par un icône à côté du nom du client par exemple ?
Aussi, serait-il possible d'afficher les clients connectés au(x) réseau(x) invité(s) ? Ils n'apparaissent pas chez moi, je ne sais pas si c'est normal :)

Merci !

**Comment by bugsounet** [comment]
J'ai pas mal d'idée a mettre en place sur ce module. (dont ce que vous avez cité !)

> Aussi, serait-il possible d'afficher les clients connectés au(x) réseau(x) invité(s)

c'est pas encore codé ;)
comme d'ailleur le debit si le client est connecté en wifi 5ghz

J'essaye de revenir des que possible sur ce module afin d'apporter quelques améliorations :)
(j'ai beaucoup de module a gérer !)

**Comment by BlackCatDeployment** [comment]
Ah oui en effet je viens de voir tes repos ! Très actif sur MM c'est cool ! Ca fait plaisir de voir un français bosser sur ce projet :)

Bon courage !

**Comment by bugsounet** [comment]
je reviens vers vous.
J'en profite du bug du firmware en v4.2

J'ai regarder un peu pour les clients connectés au(x) réseau(x) invité(s)
cela fonctionne uniquement si acces reseau local + internet ...
sinon seul le debit est remonté et le status de connexion est sur false (déconnecté)
L'api est n'est documenté pas ... donc c'est compliqué de faire plus et la remonté json ne donne pas assez d'info... ça doit etre autre part ...

La remonté des connexions / debit est viens d'etre codé pour le wifi 5g (pas encore mis sur le master)

desolé pour le retard, je bosse en parallele mes 2 autres gros modules (GoogleAssistant et Assistant2Display)

**Comment by BlackCatDeployment** [comment]
Merci pour votre retour.
Pour la liste des clients, j'imaginais quelque chose de simple comme :
<nom_client> - <IP> - <icone LAN/wifi>
si client actif et/ou joignable, à configurer dans la conf du module par ex

**Comment by bugsounet** [comment]
je vais voir ce que je peux faire pour ne pas trop surcharger et que cela reste lisible

**Comment by bugsounet** [comment]
@BlackCatDeployment :
J'ai coder avec les icones LAN/Wifi (avec force du signal), c'est sur la branch `dev` pour le moment
J'ai encore quelque test a faire avant de le mettre sur le master

**Comment by bugsounet** [comment]
J'ai coder ceci:

![](https://raw.githubusercontent.com/bugsounet/MMM-Freebox/dev/screen2.png)

 * vert: wifi 2.4Ghz
 * bleu: wifi 5 Ghz
 * j'ai mis une icone Ethernet avec un numéro pour savoir sur le port de connexion

**Comment by bugsounet** [comment]
v1.3.3 est sur le master

**Comment by BlackCatDeployment** [comment]
@bugsounet Je viens de mettre à jour votre module, il fonctionne au poil après avoir édité le config.js de MagicMirror (les paramètres liés au token ayant changé, ça me freezait complètement le miroir au chargement)
![image](https://user-images.githubusercontent.com/12493050/89952409-8159b380-dc2d-11ea-8ae2-55a730799990.png)

Reste qu'à afficher les adresses IP et c'est parfait ! :)

**Comment by bugsounet** [comment]
>Pour info, j'ai une Freebox One r2 avec la fibre et les infos remontent correctement ;)
pouvez-vous essyer le module TV pour voir si cela fonctionne avec votre box
en ajoutant symplement:
```js
player : {
  showPlayerInfo: false,
}
````

**Comment by bugsounet** [comment]
> Reste qu'à afficher les adresses IP et c'est parfait ! :)

Disponible depuis maintenant avec la version 1.4.1
La fonction `showClientIP` est desactivée par défaut, ce sera a vous de l'activer ;)

**Comment by BlackCatDeployment** [comment]
> La fonction showClientIP est desactivée par défaut, ce sera a vous de l'activer ;)

Ca fonctionne merci !

> pouvez-vous essyer le module TV pour voir si cela fonctionne avec votre box

Négatif :( Votre module fige sur le logo Freebox

**Comment by bugsounet** [comment]
si vous pouvez refaire un essai avec la v1.4.2 ?

je pense avoir resolu le souci (j'ai le meme parfois)

merci par avance pour votre aide

**Comment by BlackCatDeployment** [comment]
Négatif :
![image](https://user-images.githubusercontent.com/12493050/91741965-c8e0b900-ebb5-11ea-98e4-e0ff3ed08927.png)

Voici une partie de la configuration :
```
showClient: true,
showClientRate: true,
showClientIP: true,
showClientCnxType: true,
showFreePlayer: true,
showMissedCall: false,
showIP: false,
showPing: true,
pingAdress: "ovh.fr",
player: {
	showPlayerInfo: true,
},
debug: false,
verbose: false
```

Si je commente showPlayerInfo, ça fonctionne :
![image](https://user-images.githubusercontent.com/12493050/91742483-9f745d00-ebb6-11ea-84ed-07802c057882.png)

**Comment by bugsounet** [comment]
bon ben ... la Freeox One n'est surement pas compatible alors ;(
