### ISSUE TITLE
MMM-Freebox et Firmware 4.2.0

### ISSUE THREAD

**Issue by bugsounet** [bugsounet/MMM-Freebox#17]
Attention, le module n'est plus fonctionnel avec ce firmware (on dit ... merci Free !)
Je vais inspecter ce qui ne fonctionne plus.

Cela a l'air beaucoup grave que prévu.
Je n'arrive plus a m'enregistrer sur la Freebox
Je n'arrive plus a m'identifier sur MMM-Freebox sur la Freebox.

Pour le moment, il serait judicieux de désactiver le module malheureusement
en ajoutant `disabled: true,` avant le nom du module
exemple:
```js
{
  disabled : true,
  module: "MMM-Freebox",
  position: "top_center",
```

Je reviens vers vous dès que possible !
@busgounet

**Comment by bugsounet** [comment]
En cours de résolution...

Apres une complete réécriture du script de connexion et d'interrogation de la freebox
Je retrouve enfin quelque chose de fonctionnel !
La configuration va donc changer... et sera plus simple :)
Je vais donc créé ma propre librairie

Apres discution avec les équipes de Free, ce n'est pas un bug de ma part ... mais de leur côté ;)
Comme quoi... personne n'est parfait ;)

**Comment by bugsounet** [comment]
Souci en parti résolu (enfin contourné)

Attention a mettre en place la nouvelle configuration pour avoir le module fonctionnel :)

**Comment by BlackCatDeployment** [comment]
Pour l'instant je n'ai pas rencontré le bug avec la Freebox One.
Mais merci pour votre réactivité !
