### ISSUE TITLE
Cannot find module 'Freebox_Login.js'

### ISSUE THREAD

**Issue by mattx38** [bugsounet/MMM-Freebox#4]
Salut, 

Je viens de tenter d'installer ton module Freebox, pour pouvoir controler la qualité de mon wifi. 
Je suis comme un dingue, Free vient de me changer la box à cause de soucis de wifi, je reçois la nouvelle (Révolution), avec 2 cartes wifi (super) sauf que le wifi est hyper instable. Juste pour info, je ping Google avec plus de 100ms et la latence atteint parfois 2000ms, voire des timeout sur DegroupTest... un cauchemar. Le télétravail va être compliqué cette semaine.
Bref... j'arrête de raconter ma vie.

J'ai donc un (autre) souci avec l'installation, la Freebox ne me demande pas d'association avec le module et j'obtiens le message d'erreur suivant :

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Freebox/installer/Freebox_Login.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

MMM-Freebox is now installed !
Press [Enter] to continue

Je précise que je suis connecté en SSH sur le Pi.
Merci d'avance

**Comment by bugsounet** [comment]
ah oui ...
j'ai oublier de changer le path dans l'installer.
je vais corriger

en attendant, vous pouvez lancer le script manuellement:
```sh
cd ~/MagicMirror/modules/MMM-Freebox
node Freebox_Login.js
```

**Comment by mattx38** [comment]
Parfait merci.

Je n'ai besoin d'afficher que le ping vers Google et j'ai 2 questions : 
Comment se configure l'adresse qui est pinguée ?
J'ai essayé d'aligner le text à droite, cat j'ai mis le module à droite, mais je n'arrive pas à trouver le bon endroit où le spécifier dans le fichier MMM-Freebox.css

**Comment by bugsounet** [comment]
1. Je force vers google.fr, je vais voir pour la prochaine version pour ajouter la feature si vous le desirez
  2. [ici](https://github.com/bugsounet/MMM-Freebox/blob/master/MMM-Freebox.js#L198)

**Comment by mattx38** [comment]
Ok ce serait top pour le ping, de pouvoir indiquer l'adresse que l'on souhaite pinguer.

Pour l'alignement du texte à droite, je pensais qu'un "text_aligne : right" dans le fichier css ferait l'affaire, mais à priori non. Pouvez-vous m'indiquer ce qu'il faudrait rajouter pour que le texte soit aligné à droite ?

Je n'ai pas autant de connaissances que vous en développement. Je cherche à comprendre les rôles de chaque fichier et d'en comprendre la logique, ensuite je teste plein de choses. Je suis complètement autodidacte, mais encore trop novice dans ce domaine. C'est assez passionnant en tout cas. Encore bravo et merci pour votre disponibilité/célérité.

**Comment by bugsounet** [comment]
j'ai mis a jour et créé pingAdress pour changer l'adresse du ping

**Comment by mattx38** [comment]
Excellent j’ai vu la notification sur le miroir avant de voir votre e-mail 

Matt
