### ISSUE TITLE
DOM_OBJECTS_CREATED jamais activé

### ISSUE THREAD

**Issue by wileck** [bugsounet/MMM-Freebox#9]
Salut!

Super boulot! 
Sur mon MagicMirror l'event DOM_OBJECTS_CREATED ne se déclenche pas... Je ne sais pas si ça vient de mon mirror.

Du coup, j'ai du ajouter MODULE_DOM_CREATED ligne 63 dans MMM-Freebox.js

    switch(notification) {
      case "MODULE_DOM_CREATED":
      case "DOM_OBJECTS_CREATED":

Si jamais ça peut aider certains.
Bonne journée
Raphaël

**Comment by bugsounet** [comment]
Bonjour,

si `DOM_OBJECTS_CREATED` ne se déclanche pas, c'est qu'il y a un module en erreur
il faut donc trouver lequel par exemple en les désactivant et en les réactivant 1 à 1
sinon vous aller perturber le bon fonctionnement des autres modules

En fesant votre maniere, vous allez casser le lien du fichier vers github et donc mettre  ce fichier en erreur lors de la prochaine mise a jour
Je déconseille donc cette méthode

**Comment by wileck** [comment]
Exact c'est MMM-GoogleTasks qui est en erreur ! Merci!

Au fait : votre module fonctionne avec une Mini4K fibre.
showBandWidth affiche : FTTH:1000.00/600.00 Mb/s
Le reste des infos remontées est ok.
